# Generated by Django 3.2.7 on 2021-09-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('co_introduction', models.TextField()),
                ('logo', models.ImageField(default='default.jpg', upload_to='company_logo')),
                ('link', models.CharField(max_length=80)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('experience', models.CharField(choices=[('no-matter', 'مهم نیست'), ('1-3', 'یک تا ۳ سال'), ('3-6', 'سه تا ۶ سال'), ('+6', 'بیشتر از ۶ سال')], max_length=80)),
                ('salary', models.IntegerField()),
                ('cooperation_type', models.CharField(choices=[('full-time', 'تمام وقت'), ('part-time', 'پاره وقت'), ('remote', 'دور کاری'), ('internship', 'کار آموزی')], max_length=80)),
                ('job_description', models.TextField()),
                ('skills_required', models.CharField(max_length=80)),
                ('military_service', models.CharField(choices=[('no-matter', 'مهم نیست'), ('end', 'پایان خدمت')], max_length=80)),
                ('degree', models.CharField(choices=[('no-matter', 'مهم نیست'), ('diploma', 'دیپلم'), ('bachelor', 'لیسانس')], max_length=80)),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن'), ('not-matter', 'مهم نیست')], max_length=10)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.company')),
            ],
        ),
    ]
