# Generated by Django 3.2.7 on 2021-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_company_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cooperation_type',
            field=models.CharField(choices=[('full-time', 'تمام وقت'), ('part-time', 'پاره وقت'), ('remote', 'دور کاری'), ('internship', 'کار آموزی')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('not-matter', 'مهم نیست'), ('1-3', 'یک تا ۳ سال'), ('3-6', 'سه تا ۶ سال'), ('+6', 'بیشتر از ۶ سال')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(),
        ),
    ]
