# Generated by Django 3.2.7 on 2021-09-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='is_jobseeker',
            field=models.BooleanField(default=False),
        ),
    ]
