# Generated by Django 3.2.7 on 2021-09-05 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerSaveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('saved_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='jobseeker.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='jobseeker.jobseekerprofile')),
            ],
        ),
    ]
