# Generated by Django 3.2.7 on 2021-09-26 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20210909_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 13, 58, 13, 275267)),
        ),
    ]
